name: Deploy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn workspaces foreach -pt --all run build

      - name: Deploy CDK stacks
        run: yarn workspace infra cdk deploy EdgeStack AppStack --require-approval never --outputs-file cdk-outputs.json

      - name: Sync dist to S3
        run: |
          WEB_BUCKET=$(jq -r '.AppStack.WebBucketName' packages/infra/cdk-outputs.json)
          aws s3 sync packages/web/dist s3://$WEB_BUCKET --delete

      - name: Invalidate CloudFront and report URL
        run: |
          DIST_ID=$(jq -r '.AppStack.CloudFrontDistributionId' packages/infra/cdk-outputs.json)
          FINAL_URL=$(jq -r '.AppStack.CloudFrontDistributionUrl' packages/infra/cdk-outputs.json)
          aws cloudfront create-invalidation --distribution-id $DIST_ID --paths '/*'
          echo "Application URL: $FINAL_URL"

