name: Destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: ${{ vars.AWS_REGION || 'ap-south-1' }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: ${{ vars.AWS_REGION || 'ap-south-1' }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME || '' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build

      - name: Read bucket names for cleanup
        run: |
          aws cloudformation describe-stacks --stack-name AppStack --query "Stacks[0].Outputs" > outputs.json
          WEB_BUCKET=$(jq -r '.[] | select(.OutputKey=="WebBucketName") | .OutputValue' outputs.json)
          USER_BUCKET=$(jq -r '.[] | select(.OutputKey=="UserdataBucketName") | .OutputValue' outputs.json)
          echo "WEB_BUCKET=$WEB_BUCKET" >> $GITHUB_ENV
          echo "USER_BUCKET=$USER_BUCKET" >> $GITHUB_ENV

      - name: Empty S3 buckets
        run: |
          aws s3 rm "s3://$WEB_BUCKET" --recursive || true
          aws s3 rm "s3://$USER_BUCKET" --recursive || true

      - name: Destroy AppStack
        if: env.DOMAIN_NAME == ''
        run: yarn workspace infra cdk destroy AppStack --force --require-approval never

      - name: Destroy AppStack and EdgeStack
        if: env.DOMAIN_NAME != ''
        run: yarn workspace infra cdk destroy AppStack EdgeStack --force --require-approval never

