name: Destroy infrastructure

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  destroy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCOUNT_ID: ${{ vars.AWS_ACCOUNT_ID }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      CDK_DEFAULT_ACCOUNT: ${{ vars.AWS_ACCOUNT_ID }}
      CDK_DEFAULT_REGION: ${{ vars.AWS_REGION }}
      DOMAIN_NAME: ${{ vars.DOMAIN_NAME }}
      HOSTED_ZONE_ID: ${{ vars.HOSTED_ZONE_ID }}
      ENABLE_WEEKLY_LAMBDA: ${{ vars.ENABLE_WEEKLY_LAMBDA }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: yarn

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build
        run: yarn build

      - name: Generate CDK outputs
        run: yarn workspace infra cdk synth
        continue-on-error: true

      - name: Empty S3 buckets
        run: |
          if [ -f packages/infra/cdk-outputs.json ]; then
            WEB_BUCKET=$(jq -r '.AppStack.WebBucketName' packages/infra/cdk-outputs.json | tr '.' '-')
            USER_BUCKET=$(jq -r '.AppStack.UserdataBucketName' packages/infra/cdk-outputs.json | tr '.' '-')
            aws s3 rm "s3://$WEB_BUCKET" --recursive || true
            aws s3 rm "s3://$USER_BUCKET" --recursive || true
          else
            echo "cdk-outputs.json not found. Skipping bucket cleanup."
          fi

      - name: Destroy CDK stacks
        run: yarn workspace infra cdk destroy --all --force -c domain=$DOMAIN_NAME -c hostedZoneId=$HOSTED_ZONE_ID -c enableWeeklyLambda=$ENABLE_WEEKLY_LAMBDA
